TypeError: unorderable types: list() >= int() in command send_queued_messages
With django 1.10.5 and django-mail-queue 3.0 below error occurs.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/mailqueue/management/commands/send_queued_messages.py", line 22, in handle
    MailerMessage.objects.send_queued(limit=options['limit'])
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/mailqueue/models.py", line 24, in send_queued
    for email in self.filter(sent=False)[:limit]:
  File "/opt/myvirtual/mmc_env/lib/python3.5/site-packages/django/db/models/query.py", line 274, in __getitem__
    (k.stop is None or k.stop >= 0))), \
TypeError: unorderable types: list() >= int()